sudo: false
language: java
jdk:
  - openjdk7
install: true
script:
  - mvn -Ptravis --fail-at-end verify
  - jdk_switcher use oraclejdk8
  - mvn -Ptravis --fail-at-end verify -Declipse.target=neon
cache:  
  directories:
   - $HOME/.m2

