sudo: false
language: java
jdk:
  - openjdk7
install: true
script:
  - mvn -Ptravis verify
  - jdk_switcher use oraclejdk8
  - mvn -Ptravis verify -Declipse.target=neon
cache:  
  directories:
   - $HOME/.m2

