sudo: false
language: java
jdk:
  - openjdk7
install: 
  # download Cloud SDK
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-125.0.0-linux-x86_64.tar.gz
  - tar -xzf google-cloud-sdk-125.0.0-linux-x86_64.tar.gz
  # update all Cloud SDK components
  - gcloud components update --quiet
  # add App Engine component to Cloud SDK
  - gcloud components install app-engine-java --quiet
env:
  global:
    - PATH=$PWD/google-cloud-sdk/bin:$PATH
    - CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
    - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 3 # give metacity some time to start
script:
  - mvn -Ptravis --fail-at-end verify
  - jdk_switcher use oraclejdk8
  - mvn -Ptravis --fail-at-end verify -Declipse.target=neon
addons:
  apt:
    packages:
      - metacity
cache:
  directories:
   - $HOME/.m2

