sudo: false
language: java
jdk:
  - openjdk7
install: true
before_install:
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-104.0.0-linux-x86_64.tar.gz
  - tar -xzvf google-cloud-sdk-104.0.0-linux-x86_64.tar.gz
  - ./google-cloud-sdk/bin/gcloud components list
  - ./google-cloud-sdk/bin/gcloud components install app-engine-java
script:
  - mvn -Ptravis verify
  - jdk_switcher use oraclejdk8
  - mvn -Ptravis verify -Declipse.target=neon
cache:
  directories:
   - $HOME/.m2

